# aliases for common git commands
alias g='git'
alias st='git status -s'
alias send='git push origin'
alias commit='git commit -m '
#alias log='git log'
#alias stash='git stash'
#alias checkout='git checkout'
alias branch='git branch'
alias giveme='git pull origin '
#alias fetch='git fetch'
#alias merge='git merge'
#alias cherry-pick='git cherry-pick'
#alias rebase='git rebase'