# aliases for common git commands
alias g='git'
alias st='git status -s'
alias push='git push origin'
alias commit='git commit -m '
alias branch='git branch'
alias pull='git pull origin '
alias fetch='git fetch'
alias merge='git merge'
alias add='git add . '
